### ISSUE TITLE
You sure implement the MMCA?

### ISSUE THREAD

**Issue by LikeGiver** [kyegomez/MMCA#6]
Not to offense, but after reading the code of MultiModalCausalAttention in mmca/main, I think it's a Cross Attention(CrA described in the paper) instead of the new attention Multi-Modal Causal Attention Mechanism (MMCA), and the so-called SimpleMMCA class is also a Cross Attention.

The official code of MMCA attention is in this location: [https://github.com/microsoft/DeepSpeedExamples/blob/master/applications/DeepSpeed-VisualChat/utils/model/third_party_model/hf_model/modeling_llama.py](url)

That being said, I must acknowledge the hard work and dedication that has gone into creating this code. Your README.md is correct and instructive.Thank you for your work and for sharing it with the community.

**Comment by kyegomez** [comment]
@LikeGiver how can I improve the code?
